### ISSUE TITLE
Admin interface documentation outdated?

### ISSUE THREAD

**Issue by thomasbalsloev** [assaf/rack-oauth2-server#5]
Hi.

First of all, thank you for a great gem!

When I followed the configuration doc on how to set up the Admin interface I ran into this error:

.../config/application.rb:54: undefined method `set' for #Module:0xb6980984 (NoMethodError)

I have added this to my application.rb:
# Configure OAuth2 Admin interface

```
config.after_initialize do
  Rack::OAuth2::Server::Admin.set :client_id, "XXX"
  Rack::OAuth2::Server::Admin.set :client_secret, "XXX"
  Rack::OAuth2::Server::Admin.set :scope, %w{read write}
end
```

If I include Sinatra like this: require 'sinatra', in the application.rb file I get this error:

../config/application.rb:55: private method `set' called for #Module:0xb67023c4 (NoMethodError)

Seems like it's not possible at all to use "set" like it is described in the doc?
How can I get the Admin interface to work?

Best regards,
Thomas.

**Comment by rafael** [comment]
I'm having this issue as well. Were you able to figure it out?

**Comment by rafael** [comment]
It seems that you need to require "rack/oauth2/server/admin" in order to make it work.
Shouldn't you add this to rack-oauth2-server.rb?

Thanks!

**Comment by thomasbalsloev** [comment]
Hi Rafael!

Sadly I hadn't had time to look at this before now.
Great that you figured it out. Thanks! :o)

Closing this issue...

Thomas.
